# Change these first
owner: zYxDevs # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Personal Blog
    url: https://www.isekai.eu.org
  - name: Otaku Fanshare
    url: https://www.otakufanshare.eu.org
  - name: zYxDevs Haste
    url: http://paste.isekai.eu.org
  - name: Git Alert Bot
    url: http://galert.isekai.eu.org
  - name: Ninym Robot
    url: http://18.132.101.53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.isekai.eu.org
  # baseUrl: /your-repo-name
  theme: dark
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "**Status Dashboard** is the place where you can see all my site uptime status."
  introMessage: This status is **real-time**, This service is open source on [GitHub repository](https://github.com/upptime/upptime).
  navbar:
    - title: Home
      href: https://www.isekai.eu.org
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Telegram
      href: https://t.me/Yoga_CIC

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
