# Change these first
owner: zYxDevs # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Personal Blog
    url: https://www.isekai.eu.org
  - name: Otaku Fanshare
    url: https://www.otakufanshare.eu.org
  - name: IsekaiBin
    url: https://paste.isekai.eu.org
  - name: Isekai Safelink
    url: https://safe.isekai.eu.org
  - name: TorrentApi
    url: https://torapi.isekai.eu.org
  - name: Screenshot Api
    url: https://webshot.otakufanshare.eu.org
  - name: Kusonime API
    url: https://kuso.otakufanshare.eu.org/api
  - name: Wibu API
    url: https://wibu-api.vercel.app/docs
  - name: Janda RESTful API
    url: http://janda.zyxdevs.eu.org
  - name: Git Alert
    url: http://galert.isekai.eu.org
  - name: YoDrive
    url: https://yodrive.eu.org
  - name: zYxDrive
    url: https://zyxdrive.eu.org
  - name: zYxDrive [SA]
    url: https://index.isekai.eu.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.isekai.eu.org
  # baseUrl: /your-repo-name
  theme: dark
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: zYxDevs Site Status
  introTitle: "**Status Dashboard** is the place where you can see all my site uptime status."
  introMessage: This status is **real-time**, [Donation are welcome](https://www.isekai.eu.org/page/donation) to kept all site online.
  navbar:
    - title: Home
      href: /
    - title: Blog
      href: https://www.isekai.eu.org
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Telegram
      href: https://t.me/Yoga_CIC

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
